"use client";

import { useState } from "react";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import { DarkModeProvider } from "./components/DarkModeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const toggleSidebar = () => setIsSidebarOpen(!isSidebarOpen);

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" />
        <title>My Personal Assistant</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeProvider>
          {/* Main Container */}
          <div className="flex flex-col min-h-screen">
            {/* Navbar */}
            <Navbar toggleSidebar={toggleSidebar} />

            {/* Content Area */}
            <div className="flex flex-1 mt-16">
              {/* Sidebar */}
              <Sidebar isOpen={isSidebarOpen} toggleSidebar={toggleSidebar} />

              {/* Page Content */}
              <main className="flex-1 p-3 bg-gray-50 dark:bg-gray-900">
                {children}
              </main>
            </div>
          </div>
        </DarkModeProvider>
      </body>
    </html>
  );
}
